experimentName: gbm_autoencoder
trialConcurrency: 1
maxExperimentDuration: 2h
maxTrialNumber: 100
searchSpaceFile: search_space_ae.json
useAnnotation: false
trialCommand: python autoencoder_search.py
trialCodeDirectory: .
trialGpuNumber: 0
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
